name: Build Godot
description: Build Godot with the provided options.
inputs:
  target:
    description: The scons target (debug/release_debug/release).
    default: "debug"
  tools:
    description: If tools are to be built.
    default: false
  tests:
    description: If tests are to be built.
    default: false
  platform:
    description: The Godot platform to build.
    required: false
  sconsflags:
    default: ""
  scons-cache:
    description: The scons cache path.
    default: "${{ github.workspace }}/.scons-cache/"
  scons-cache-limit:
    description: The scons cache size limit.
    default: 4096
  mono-exe:
    description: Add exe surfix after binary file
    default: ""
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: sh
      env:
          SCONSFLAGS: ${{ inputs.sconsflags }}
          SCONS_CACHE: ${{ inputs.scons-cache }}
          SCONS_CACHE_LIMIT: ${{ inputs.scons-cache-limit }}
      run: |
        # echo "Generating Glue Program..."
        # scons p=${{ inputs.platform }} arch=x86_64 target=${{ inputs.target }} tools=yes module_mono_enabled=yes mono_glue=no --jobs=2 ${{ env.SCONSFLAGS }}
        # ls -l bin/
        # bin/godot.${{ inputs.platform }}.opt.tools.x86_64.mono${{ inputs.mono-exe }} --generate-mono-glue modules/mono/glue
        # echo "Packing..."
        scons p=${{ inputs.platform }} arch=x86_64 target=${{ inputs.target }} tools=yes module_mono_enabled=yes --jobs=2 ${{ env.SCONSFLAGS }}
        ls -l bin/
