name: 🍎 macOS Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: gm
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: macos-editor
            target: release_debug
            tools: true
            bin: "./bin/godot.osx.tools.64.mono"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: osx
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Build Package
        run: |
          cp -r misc/dist/osx_tools.app ./bin/Godot.app
          mkdir -p ./bin/Godot.app/Contents/MacOS
          cp bin/godot.osx.opt.tools.x86_64.mono ./bin/Godot.app/Contents/MacOS/Godot
          chmod +x ./bin/Godot.app/Contents/MacOS/Godot

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
