name: 🏁 Windows Builds
on: [push, pull_request]

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_BASE_BRANCH: gm
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: windows-editor
            target: release_debug
            tools: true
            bin: "./bin/godot.windows.tools.64.mono.exe"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }} 
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps
      
      - name: Setup Mono
        shell: powershell
        run: |
          curl.exe https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0.107-x64-0.msi --output mono-6.12.0.107-x64-0.msi
          Start-Process -FilePath msiexec -ArgumentList /i, mono-6.12.0.107-x64-0.msi, /qn -Wait
          [environment]::SetEnvironmentvariable("Path", [environment]::GetEnvironmentvariable("Path", "User") + "C:\Program Files\Mono\bin", "User")
          [environment]::GetEnvironmentvariable("Path", "User")
          ls "C:\Program Files\Mono"

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: windows
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          scons-cache-limit: 3072
          mono-exe: ".exe"

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
